# Service Post \uC124\uC815
server:
  port: 9091

# Log Level \uC124\uC815
logging:
  level:
    root: info

# ActiveMQ \uC5F0\uACB0 \uC815\uBCF4
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

# Activemq queue \uC815\uBCF4
activemq:
  queue.name: sample.queue