# SERVER ??
server:
  port: 9095

# RabbitMQ ??
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# RabbitMQ Queue, Routing, Exchange ??
rabbitmq:
  exchange:
    name: queue.subject
  queue:
    stk:
      name: queue.subject.stk
    ste:
      name: queue.subject.ste
  routing:
    stk:
      key: routing.subject.stk
    ste:
      key: routing.subject.ste

logging:
  level:
    root: debug



