# Service Post 설정
server:
  port: 9091

# Log Level 설정
logging:
  level:
    root: info

# RabbitMQ 연결 정보
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# RabbitMQ queue, exchange, routing-key 정보
rabbitmq:
  queue.name: sample.queue
  exchange.name: sample.exchange
  routing.key: sample.key